### ISSUE TITLE
反転中心対称性のない直線分子のsymmetryが上手くとれない

### ISSUE THREAD

**Issue by kohei-noda-qcrg** [RQC-HU/sum_dirac_dfcoef#95]
- 以下、COの例。E1が上手く取得できていない

```bash
~/test/dirac/privec/noprivec/CO
$ cat CO.inp
**DIRAC
.TITLE
Ar
.WAVE FUNCTION
.ANALYZE
**HAMILTONIAN
.X2C
**WAVE FUNCTIONS
.SCF
**ANALYZE
.PRIVEC
**MOLECULE
*BASIS
.DEFAULT
6-31G
**INTEGRALS
*READIN
.UNCONTRACT
*END OF
~/test/dirac/privec/noprivec/CO
$ cat CO.xyz
2

C        0 0 0
O        0 0 1
~/test/dirac/privec/noprivec/CO
$ ~/software/dirac/23/share/dirac/pam --inp CO.inp --mol CO.xyz &> /dev/null
~/test/dirac/privec/noprivec/CO
$ echo $?
0
 ~/test/dirac/privec/noprivec/CO
$ sum_dirac_dfcoef -i CO_CO.out -g
Traceback (most recent call last):
  File "/home/noda/.pyenv/versions/3.9.15/bin/sum_dirac_dfcoef", line 8, in <module>
    sys.exit(main())
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/sum_dirac_dfcoef.py", line 16, in main
    header_info.read_header_info(dirac_output)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/header_info.py", line 43, in read_header_info
    self.__read_eigenvalues(dirac_output)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/header_info.py", line 55, in __read_eigenvalues
    self.eigenvalues.get_eigenvalues(dirac_output)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/eigenvalues.py", line 250, in get_eigenvalues
    current_symmetry_type, occ_idx = prepare_occupation_info(words)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/eigenvalues.py", line 105, in prepare_occupation_info
    occ_idx = {k: 1 for k in omega[current_symmetry_type].keys()}
KeyError: 'E1'

**Comment by kohei-noda-qcrg** [comment]
- デバッグプリントしてみたところ、omegaのデータがE1になるはずの部分でEになっている
```bash
~/test/dirac/privec/noprivec/CO
$ sum_dirac_dfcoef -i CO_CO.out -g
{'E': {'1/2': {1: -20.697688969739, 2: -11.342133985872, 3: -1.659778644489, 4: -0.804334527443, 5: -0.703313299383, 6: -0.538811482582, 7: 0.200165606125, 8: 0.405807011518, 9: 0.659774568437, 10: 0.701728161256, 11: 0.91676070542, 12: 1.135413939403, 13: 1.354924621075, 14: 1.690845367183, 15: 3.268869207303, 16: 3.284182553362, 17: 4.14766489869, 18: 5.754403364925, 19: 5.980242208017, 20: 7.936615598293, 21: 13.554275680505, 22: 15.590744734946, 23: 15.785657855561, 24: 25.295241481626, 25: 29.569672804844, 26: 29.740423791991, 27: 34.339346457313, 28: 64.009328510293, 29: 81.732082670006, 30: 151.284472009385, 31: 237.08404533687, 32: 430.413659341936, 33: 932.318781118632, 34: 1648.578798484126, 35: 5007.647028099138, 36: 8274.304046682402}, '3/2': {1: -0.702491589009, 2: 0.200434358324, 3: 0.659900345353, 4: 1.136190107067, 5: 3.269624451989, 6: 5.757477530971, 7: 15.597068960273, 8: 29.595677579846}}} E1
Traceback (most recent call last):
  File "/home/noda/.pyenv/versions/3.9.15/bin/sum_dirac_dfcoef", line 8, in <module>
    sys.exit(main())
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/sum_dirac_dfcoef.py", line 16, in main
    header_info.read_header_info(dirac_output)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/header_info.py", line 43, in read_header_info
    self.__read_eigenvalues(dirac_output)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/header_info.py", line 55, in __read_eigenvalues
    self.eigenvalues.get_eigenvalues(dirac_output)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/eigenvalues.py", line 251, in get_eigenvalues
    current_symmetry_type, occ_idx = prepare_occupation_info(words)
  File "/home/noda/develop/sum_dirac_dfcoef/src/sum_dirac_dfcoef/eigenvalues.py", line 106, in prepare_occupation_info
    occ_idx = {k: 1 for k in omega[current_symmetry_type].keys()}
KeyError: 'E1'
```

**Comment by kohei-noda-qcrg** [comment]
- 下記関数に問題がある
  -  FREP(IFSYM)は反転中心対称性があるときは" in E1g:"のようになるが、そうでないときは" in E1 :"のようになってE1と:の間に空白ができてしまう
  - そのため正しいsymmetryが取得できない
https://github.com/RQC-HU/sum_dirac_dfcoef/blob/826a0f28151ba9f805c9f3442248691001a166e1/src/sum_dirac_dfcoef/eigenvalues.py#L117-L126
